"""add avilable_copy

Revision ID: 20d3e8afbaff
Revises: c25ac2f0ef9c
Create Date: 2025-09-22 11:07:57.124723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20d3e8afbaff'
down_revision: Union[str, Sequence[str], None] = 'c25ac2f0ef9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('available_copies', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'available_copies')
    # ### end Alembic commands ###
