"""add userrole enum

Revision ID: 40791d8051df
Revises: 8a5d86bdd7c4
Create Date: 2025-09-21 16:18:42.156538

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '40791d8051df'
down_revision: Union[str, Sequence[str], None] = '8a5d86bdd7c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('ADMIN', 'LIBRARIAN', 'MEMBER', name='userrole'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('ADMIN', 'LIBRARIAN', 'MEMBER', name='userrole'),
               nullable=True)
    # ### end Alembic commands ###
