"""add image field to books version 3

Revision ID: e0abafd7a8fd
Revises: 3c3c6f7fb028
Create Date: 2025-10-02 01:20:45.121973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0abafd7a8fd'
down_revision: Union[str, Sequence[str], None] = '3c3c6f7fb028'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
